apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - autoscaling.aibrix.ai_podautoscalers.yaml
  - model.aibrix.ai_modeladapters.yaml
  - orchestration.aibrix.ai_kvcaches.yaml
  - orchestration.aibrix.ai_podsets.yaml
  - orchestration.aibrix.ai_rayclusterfleets.yaml
  - orchestration.aibrix.ai_rayclusterreplicasets.yaml
  - orchestration.aibrix.ai_rolesets.yaml
  - orchestration.aibrix.ai_stormservices.yaml
